apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubernetes-image-puller-operator-role-binding
  namespace: kubernetes-image-puller-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubernetes-image-puller-operator-role
subjects:
- kind: ServiceAccount
  name: kubernetes-image-puller-operator-sa
  namespace: kubernetes-image-puller-operator
