#
# Copyright (c) 2019-2023 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  labels:
    name: kubernetes-image-puller-operator
spec:
  selector:
    matchLabels:
      name: kubernetes-image-puller-operator
  replicas: 1
  template:
    metadata:
      labels:
        name: kubernetes-image-puller-operator
    spec:
      serviceAccountName: $(CONTROLLER_SERVICE_ACCOUNT)
      containers:
      - name: kubernetes-image-puller-operator
        image: quay.io/eclipse/kubernetes-image-puller-operator:next
        command:
        - /manager
        args:
        - --leader-elect
        imagePullPolicy: Always
        env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: "kubernetes-image-puller-operator"     
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 64Mi
      terminationGracePeriodSeconds: 10
