# This has to be a separate kustomize file, since namePrefix below cannot be
# disabled for specific types, and we need the CSV's .metadata.name to be unchanged

namePrefix: kubernetes-image-puller-operator-

bases:
- ../../../default

# These patches remove the unnecessary "cert" volume and its manager container volumeMount.
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: manager
  patch: |-
    # Remove the manager container's "cert" volumeMount, since OLM will create and mount a set of certs.
    # Update the indices in this path if adding or removing containers/volumeMounts in the manager's Deployment.
    - op: remove
      path: /spec/template/spec/containers/0/volumeMounts/0
    # Remove the "cert" volume, since OLM will create and mount a set of certs.
    # Update the indices in this path if adding or removing volumes in the manager's Deployment.
    - op: remove
      path: /spec/template/spec/volumes/0
