
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: service
      namespace: kubernetes-image-puller-operator
      path: /validate-che-eclipse-org-v1alpha1-kubernetesimagepuller
  failurePolicy: Fail
  name: vkubernetesimagepuller.kb.io
  rules:
  - apiGroups:
    - che.eclipse.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - kubernetesimagepullers
  sideEffects: None
