# permissions for end users to view kubernetesimagepullers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetesimagepuller-viewer-role
rules:
- apiGroups:
  - che.eclipse.org
  resources:
  - kubernetesimagepullers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - che.eclipse.org
  resources:
  - kubernetesimagepullers/status
  verbs:
  - get
