#
# Copyright (c) 2019-2023 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-binding
subjects:
- kind: ServiceAccount
  name: $(CONTROLLER_SERVICE_ACCOUNT)
  namespace: kubernetes-image-puller-operator
roleRef:
  kind: Role
  name: role
  apiGroup: rbac.authorization.k8s.io
