apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubernetes-image-puller-operator-serving-cert
  namespace: kubernetes-image-puller-operator
spec:
  dnsNames:
  - kubernetes-image-puller-operator-service.kubernetes-image-puller-operator.svc
  - kubernetes-image-puller-operator-service.kubernetes-image-puller-operator.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: kubernetes-image-puller-operator-selfsigned-issuer
  secretName: kubernetes-image-puller-operator-service-cert
