apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-image-puller-operator-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubernetes-image-puller-operator-proxy-role
subjects:
- kind: ServiceAccount
  name: kubernetes-image-puller-operator-sa
  namespace: kubernetes-image-puller-operator
