apiVersion: v1
kind: Service
metadata:
  labels:
    name: kubernetes-image-puller-operator
  name: kubernetes-image-puller-operator-manager-metrics-service
  namespace: kubernetes-image-puller-operator
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    name: kubernetes-image-puller-operator
