apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: kubernetes-image-puller-operator-preview-catalog
  namespace: olm
spec:
  sourceType: grpc
  image: quay.io/eclipse/image-puller-catalog-source:latest
  updateStrategy:
    registryPoll:
      interval: 5m
