#
# Copyright (c) 2019-2024 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

name: PR check
on: pull_request
permissions:
  contents: read
jobs:
  unit-tests:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout source code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      with:
        persist-credentials: false
    - name: Set up Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
      with:
        go-version: '1.26'
    - name: Run unit tests
      run: make test
  image-build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout source code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      with:
        persist-credentials: false
    - name: Build image
      run: docker build -f build/Dockerfile --build-arg SKIP_TESTS=true .
  scorecard:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - name: Start minikube cluster
        id: run-minikube
        uses: che-incubator/setup-minikube-action@fbf2aa1144e0088e9200fc2ecf5e26040ea2a8e4 # next
        with:
          minikube-version: v1.38.1
      - name: Wait for cluster readiness
        run: |
          kubectl wait --for=condition=Ready nodes --all --timeout=120s
          kubectl wait --for=condition=Ready pods --all -n kube-system --timeout=120s
      - name: Run tests
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_wait_seconds: 30
          command: |
            make download-operator-sdk
            bin/operator-sdk olm install --version v0.28.0
            bin/operator-sdk scorecard bundle --wait-time 120s
